// Framer Motion presets — generated by designlang (motionlang)
// Source: https://vercel.com/academy/build-ai-agent-harness
// 2026-05-24T18:49:07.162Z
//
//   import { transitions, variants } from './vercel.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeInOut: [0.25, 0.1, 0.25, 1], // 139× on page
  custom2: [0.33, 0.12, 0.15, 1], // 10× on page
  custom3: [0.4, 0, 0.2, 1], // 8× on page
  easeOut: [0.3, 0.57, 0.07, 0.95], // 4× on page
  spring: [0.31, 0.05, 0.43, 1.02], // 4× on page
  custom6: [0.39, 0.18, 0.17, 0.99], // 2× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.08,
  xs: 0.09,
  sm: 0.16,
  md: 0.3,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.16, ease: easings.easeInOut },
  fast:  { duration: 0.100, ease: easings.easeInOut },
  slow:  { duration: 0.288, ease: easings.easeInOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.040 } },
  },
};

export default { easings, durations, transitions, variants };
